version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: s3dm_db
      POSTGRES_USER: s3dm_user
      POSTGRES_PASSWORD: s3dm_password
    volumes:
      - ./db:/var/lib/postgresql/data # Persistent data
    ports:
      - "5432:5432" # Expose for local development/debugging

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  gars:
    build: ./services/gars
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/gars:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://s3dm_user:s3dm_password@db:5432/s3dm_db

  rsps:
    build: ./services/rsps
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/rsps:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
      - rabbitmq
      - gars # RSPS depends on GARS for agent discovery
    environment:
      DATABASE_URL: postgresql://s3dm_user:s3dm_password@db:5432/s3dm_db
      GARS_URL: http://gars:8000 # Internal Docker network URL

  ztdigs:
    build: ./services/ztdigs
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/ztdigs:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://s3dm_user:s3dm_password@db:5432/s3dm_db

  llos:
    build: ./services/llos
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./services/llos:/app
    ports:
      - "8004:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://s3dm_user:s3dm_password@db:5432/s3dm_db

  ui-ds:
    build: ./services/ui-ds
    # For a simple static file server, you might use Nginx or Python's http.server
    # For React/Vue, you'd run 'npm start' or 'npm run dev'
    command: python3 -m http.server 8000 # Simple placeholder for static files
    volumes:
      - ./services/ui-ds:/app
    ports:
      - "8000:8000" # UI will be on port 8000
    depends_on:
      - gars
      - rsps
      - ztdigs
      - llos